---
katavti_images_registry_namespace: docker.io/lutraman
katavti_images_source_dir: "{{ playbook_dir }}/../.."
katavti_images_platform: linux/amd64
katavti_images_build_missing: false
katavti_images_key_vault_name: ""
katavti_images_google_client_id_secret: katavti-google-client-id
